### PR TITLE
configuring end-effectors and renaming planning groups to be compatible MoveIt and SimpleGrasps

### PR DESCRIPTION
**Pull request by nlyubova**
I've regenerated the MoveIt config based on the current URDF, added end-effectors, and adapted the planning groups names for using with MoveIt and MoveIt SimpleGrasps, so there are many changes, but in this configuration, it works and grasps and does not shake !

### CODE REVIEW

**Comment by vrabaud** [comment]
please rebase and create several commits: you also add a launch file for joystick in there: it deserves to be its own commit for example.

**Comment by nlyubova** [comment]
@vrabaud, thanks for your advice :) I hope it looks better:
- the first commit is still huge but it is the result from moveit_setup_assistant 
- the second is the Octomap configuration. 
The joystick file is auto-generated by the assistant as well, but it is better to skip it since it was not tested.

**Comment by vrabaud** [comment]
please rebase

**Comment by vrabaud** [comment]
Much easier to understand, thx. Please rebase, fix the few things and we're good to go.

**Comment by vrabaud** [comment]
that was good, why did you close it ? You just had to do: ```git pull --rebase origin master``` and you were done.

**Comment by nlyubova** [comment]
oops very sorry, how could I get back?

On Tue, Oct 20, 2015 at 6:58 PM, Vincent Rabaud <notifications@github.com>
wrote:

> that was good, why did you close it ? You just had to do: git pull
> --rebase origin master and you were done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ros-aldebaran/romeo_moveit_config/pull/3#issuecomment-149632549>
> .
>



-- 
Natalia Lyubova, PhD
Scientist, R&D
Aldebaran Robotics
www.aldebaran.com
+33 6 50 51 74 11

**Comment by vrabaud** [comment]
if you got your commits back, you should have a ```reopen ``` button right below that comment, just click it.

**Pull request closed without merging**
