### PR TITLE
fixing legs planning groups

### PR DESCRIPTION
**Pull request by nlyubova**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Renaming looks good to me. Np for moving from a chain definition to a joint listing in each group.

I have trouble to understand the use of `foot_virtual`. Could you give more context about what it is used for and why ?
AFAIK Virtual joints are supposed to create virtual links to emulate environment information that is not published by the robot by default (e.g. odometry). But in this case `foot_virtual_joint` it is a fixed joint connected to the left foot plant `l_sole` that is a real link already attached to a joint and published by the robot. So why is a virtual joint needed in this case ? 
Given that it is a fixed joint tied to the left foot, what happens if the right leg moves ?  `foot_virtual_joint` will stay the same, is that correct ? Is that the wanted behavior?

**Comment by nlyubova** [comment]
Thank you,
foot_virtual was in the tutorial for the whole_body control. If you think that it is not needed then I remove it

**Comment by nlyubova** [comment]
Regarding list of joints, I need it like that to make the whole-body working. I'm working on it at the moment and it should be like that : one group of joints and one group as a chain

**Comment by mikaelarguedas** [comment]
Great, looks good to me,
+1 for squash and merge

**Pull request merged**
